"""
Writing Agent
-------------
Converts Research Agent and Analysis Agent outputs into a clear,
structured final response.

Important:
- The Writing Agent preserves useful topic-specific research.
- It does not replace detailed research with generic statements.
- It keeps the existing section names required by the project tests.
"""


class WritingAgent:
    """
    Writing agent responsible for creating the final structured response.
    """

    def __init__(self):
        self.name = "Writing Agent"

    # ------------------------------------------------------------------
    # Utility Methods
    # ------------------------------------------------------------------

    def _clean_text(self, text: str) -> str:
        """Clean unnecessary whitespace while preserving content."""

        if not text:
            return ""

        lines = text.splitlines()

        cleaned_lines = []

        for line in lines:
            cleaned = line.strip()

            if cleaned:
                cleaned_lines.append(cleaned)

        return "\n".join(cleaned_lines)

    def _extract_section(
        self,
        research_data: str,
        section_title: str
    ) -> str:
        """
        Extract a Markdown section from Research Agent output.

        Example:
            ## 1. Introduction
            content...
            ## 2. Research Summary
            content...

        Returns only the requested section content.
        """

        if not research_data:
            return ""

        lines = research_data.splitlines()

        target = section_title.lower().strip()

        collecting = False
        collected = []

        for line in lines:
            stripped = line.strip()

            # Detect Markdown headings.
            if stripped.startswith("#"):
                heading = stripped.lstrip("#").strip().lower()

                if heading == target:
                    collecting = True
                    continue

                if collecting:
                    break

            if collecting:
                collected.append(line)

        return self._clean_text("\n".join(collected))

    def _extract_any_section(
        self,
        research_data: str,
        possible_titles
    ) -> str:
        """Try multiple possible section names."""

        for title in possible_titles:
            result = self._extract_section(
                research_data,
                title
            )

            if result:
                return result

        return ""

    def _remove_memory_marker(self, text: str) -> str:
        """
        Remove the internal MEMORY-AWARE marker from final user-facing
        content while preserving the actual research.
        """

        if not text:
            return ""

        lines = text.splitlines()
        result = []

        skip_memory_block = False

        for line in lines:
            lower = line.strip().lower()

            if lower == "### memory-aware":
                skip_memory_block = True
                continue

            if skip_memory_block:
                if line.strip().startswith("#"):
                    skip_memory_block = False
                elif not line.strip():
                    continue
                else:
                    continue

            if not skip_memory_block:
                result.append(line)

        return self._clean_text("\n".join(result))

    # ------------------------------------------------------------------
    # Section Extraction
    # ------------------------------------------------------------------

    def _build_research_sections(
        self,
        research_data: str
    ) -> dict:
        """
        Extract the important sections generated by the Research Agent.
        """

        cleaned_research = self._remove_memory_marker(
            research_data
        )

        sections = {
            "introduction": self._extract_any_section(
                cleaned_research,
                [
                    "1. Introduction",
                    "Introduction"
                ]
            ),

            "research_summary": self._extract_any_section(
                cleaned_research,
                [
                    "2. Research Summary",
                    "Research Summary"
                ]
            ),

            "benefits": self._extract_any_section(
                cleaned_research,
                [
                    "3. Key Benefits",
                    "Key Benefits",
                    "Benefits"
                ]
            ),

            "risks": self._extract_any_section(
                cleaned_research,
                [
                    "4. Risks and Limitations",
                    "Risks and Limitations",
                    "Risks"
                ]
            ),

            "applications": self._extract_any_section(
                cleaned_research,
                [
                    "5. Practical Applications",
                    "Practical Applications",
                    "Applications"
                ]
            ),

            "challenges": self._extract_any_section(
                cleaned_research,
                [
                    "6. Challenges",
                    "Challenges"
                ]
            ),

            "trends": self._extract_any_section(
                cleaned_research,
                [
                    "7. Current Trends",
                    "Current Trends",
                    "Trends"
                ]
            ),

            "validation": self._extract_any_section(
                cleaned_research,
                [
                    "8. Validation Considerations",
                    "Validation Considerations"
                ]
            ),

            "conclusion": self._extract_any_section(
                cleaned_research,
                [
                    "9. Conclusion",
                    "Conclusion"
                ]
            ),
        }

        return sections

    # ------------------------------------------------------------------
    # Fallback Content
    # ------------------------------------------------------------------

    def _fallback_section(
        self,
        section_name: str,
        user_request: str
    ) -> str:
        """
        Provide a small fallback only when the Research Agent did not
        provide that section.
        """

        request = user_request.strip()

        fallbacks = {
            "introduction": (
                f"This response provides a structured overview of "
                f"{request}, including its main concepts, benefits, "
                f"applications, risks, challenges, and practical "
                f"considerations."
            ),

            "research_summary": (
                f"The research focuses on the main concepts and practical "
                f"considerations associated with {request}."
            ),

            "benefits": (
                "- Can support efficiency and automation.\n"
                "- Can help analyze information and support decisions."
            ),

            "risks": (
                "- Incorrect results may affect decisions.\n"
                "- Data quality, privacy, and security should be considered."
            ),

            "applications": (
                "- Can be applied to practical workflows depending on "
                "the requirements and intended use case."
            ),

            "challenges": (
                "Implementation may require suitable data, technical "
                "resources, security, integration, and monitoring."
            ),

            "trends": (
                "Current implementations increasingly focus on automation, "
                "scalability, security, responsible use, and integration."
            ),

            "validation": (
                "The information should be validated against the actual "
                "requirements, available data, security requirements, "
                "operational constraints, and implementation environment."
            ),

            "conclusion": (
                f"{request} can provide practical value when implemented "
                "appropriately and evaluated against the requirements of "
                "the intended use case."
            ),
        }

        return fallbacks.get(
            section_name,
            "No additional information was provided."
        )

    # ------------------------------------------------------------------
    # Main Writing Method
    # ------------------------------------------------------------------

    def write(
        self,
        research_data: str,
        analysis_data: str,
        requested_format: str = "structured response",
        user_request: str = ""
    ) -> str:
        """
        Create the final response.

        Parameters
        ----------
        research_data:
            Output from the Research Agent.

        analysis_data:
            Output from the Analysis Agent.

        requested_format:
            Desired output format.

        user_request:
            Original user request.
        """

        research_data = research_data or ""
        analysis_data = analysis_data or ""
        user_request = user_request or ""

        sections = self._build_research_sections(
            research_data
        )

        # --------------------------------------------------------------
        # Ensure all required sections have content.
        # --------------------------------------------------------------

        for key in sections:
            if not sections[key]:
                sections[key] = self._fallback_section(
                    key,
                    user_request or "the requested topic"
                )

        # --------------------------------------------------------------
        # Introduction
        # --------------------------------------------------------------

        output = []

        output.append("# Answer")

        output.append("## 1. Introduction")
        output.append(
            sections["introduction"]
        )

        # --------------------------------------------------------------
        # Research Summary
        # --------------------------------------------------------------

        output.append("## 2. Research Summary")
        output.append(
            sections["research_summary"]
        )

        # --------------------------------------------------------------
        # Key Benefits
        # --------------------------------------------------------------

        output.append("## 3. Key Benefits")
        output.append(
            sections["benefits"]
        )

        # --------------------------------------------------------------
        # Risks and Limitations
        # --------------------------------------------------------------

        output.append("## 4. Risks and Limitations")
        output.append(
            sections["risks"]
        )

        # --------------------------------------------------------------
        # Practical Applications
        # --------------------------------------------------------------

        output.append("## 5. Practical Applications")
        output.append(
            sections["applications"]
        )

        # --------------------------------------------------------------
        # Analysis
        # --------------------------------------------------------------

        output.append("## 6. Analysis")

        if analysis_data.strip():
            output.append(
                self._clean_text(analysis_data)
            )
        else:
            output.append(
                "The available research was reviewed for relevance, "
                "main concepts, practical applications, benefits, risks, "
                "and limitations."
            )

        # --------------------------------------------------------------
        # Challenges
        # --------------------------------------------------------------

        output.append("## 7. Challenges")
        output.append(
            sections["challenges"]
        )

        # --------------------------------------------------------------
        # Current Trends
        # --------------------------------------------------------------

        output.append("## 8. Current Trends")
        output.append(
            sections["trends"]
        )

        # --------------------------------------------------------------
        # Validation Considerations
        # --------------------------------------------------------------

        output.append("## 9. Validation Considerations")
        output.append(
            sections["validation"]
        )

        # --------------------------------------------------------------
        # Conclusion
        # --------------------------------------------------------------

        output.append("## 10. Conclusion")
        output.append(
            sections["conclusion"]
        )

        final_output = "\n\n".join(output)

        return final_output


# ----------------------------------------------------------------------
# Manual Test
# ----------------------------------------------------------------------

if __name__ == "__main__":

    research = """
    # Artificial Intelligence in Healthcare

    ## 1. Introduction

    Artificial Intelligence (AI) in healthcare refers to the use of
    computational systems to analyze healthcare data, identify patterns,
    support predictions, automate selected tasks, and assist healthcare
    professionals.

    ## 2. Research Summary

    AI in healthcare can process medical images, electronic health records,
    laboratory results, clinical notes, and patient monitoring data.

    ## 3. Key Benefits

    - Faster analysis of healthcare data.
    - Support for clinical decision-making.
    - Automation of repetitive tasks.
    - Improved workflow efficiency.

    ## 4. Risks and Limitations

    - Incorrect predictions.
    - Data bias.
    - Patient privacy concerns.
    - Security risks.
    - Need for human oversight.

    ## 5. Practical Applications

    - Medical imaging.
    - Disease prediction.
    - Clinical decision support.
    - Patient monitoring.
    - Drug discovery.

    ## 6. Challenges

    - Data quality.
    - Privacy.
    - Explainability.
    - System integration.

    ## 7. Current Trends

    - AI-assisted medical imaging.
    - Predictive healthcare analytics.
    - Responsible AI.
    - Healthcare data security.

    ## 8. Validation Considerations

    Healthcare AI systems should be validated for reliability,
    safety, privacy, security, and suitability for the intended
    healthcare environment.

    ## 9. Conclusion

    AI can support healthcare through data analysis, decision support,
    automation, and personalized care when appropriately validated
    and monitored.
    """

    analysis = """
    Analysis Topic: Artificial Intelligence in Healthcare

    The research is relevant to the requested healthcare AI topic.
    """

    agent = WritingAgent()

    result = agent.write(
        research,
        analysis,
        user_request="Research artificial intelligence in healthcare"
    )

    print(result)